import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#8B1A1A',
        'primary-container': '#ffdad6',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb3ac',
        'on-primary': '#ffffff',
        'on-primary-container': '#ff9a91',
        'on-primary-fixed': '#410003',
        'on-primary-fixed-variant': '#8a1a1a',
        'inverse-primary': '#ffb3ac',
        secondary: '#5d5f5d',
        'secondary-container': '#e2e3e1',
        'secondary-fixed': '#e2e3e1',
        'secondary-fixed-dim': '#c6c7c5',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#636563',
        'on-secondary-fixed': '#1a1c1b',
        'on-secondary-fixed-variant': '#454746',
        tertiary: '#2f3131',
        'tertiary-container': '#454748',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#b5b5b6',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        background: '#F2F2F0',
        'on-background': '#1c1b1b',
        surface: '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-variant': '#e5e2e1',
        'surface-tint': '#8B1A1A',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#58413f',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#8c716e',
        'outline-variant': '#e0bfbc',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        sm: '0.25rem',
        lg: '0.625rem',
        xl: '1rem',
        '2xl': '1.25rem',
        full: '9999px',
      },
      boxShadow: {
        xs: '0 1px 2px 0 rgb(0 0 0 / 0.04)',
        sm: '0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.04)',
        DEFAULT: '0 2px 8px 0 rgb(0 0 0 / 0.07), 0 1px 3px -1px rgb(0 0 0 / 0.04)',
        md: '0 4px 12px -2px rgb(0 0 0 / 0.09), 0 2px 4px -2px rgb(0 0 0 / 0.05)',
        lg: '0 8px 24px -4px rgb(0 0 0 / 0.11), 0 4px 8px -4px rgb(0 0 0 / 0.06)',
        xl: '0 16px 40px -8px rgb(0 0 0 / 0.13), 0 8px 16px -8px rgb(0 0 0 / 0.07)',
        card: '0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.03)',
        'card-hover': '0 4px 16px -2px rgb(0 0 0 / 0.10), 0 2px 6px -2px rgb(0 0 0 / 0.05)',
        inner: 'inset 0 1px 2px 0 rgb(0 0 0 / 0.05)',
        none: 'none',
      },
      spacing: {
        'stack-xl': '64px',
        'stack-lg': '32px',
        'stack-md': '16px',
        'stack-sm': '8px',
        'margin-desktop': '40px',
        gutter: '24px',
        'sidebar-width': '280px',
        'max-content-width': '1160px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        serif: ['Merriweather', 'serif'],
        'headline-lg': ['"Plus Jakarta Sans"'],
        'headline-md': ['"Plus Jakarta Sans"'],
        'headline-sm': ['"Plus Jakarta Sans"'],
        'label-md': ['"Plus Jakarta Sans"'],
        'label-sm': ['"Plus Jakarta Sans"'],
        'display-lg': ['"Plus Jakarta Sans"'],
        'body-lg': ['Merriweather'],
        'body-md': ['Merriweather'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.8', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
} satisfies Config
